SELECT DISTINCT
  ?item
  ?countryLabel
WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?item p:P31 ?statement0.
  ?statement0 (ps:P31/(wdt:P279*)) wd:%s.
  ?item wdt:P17 ?country.
  MINUS {?item wdt:P31 wd:Q11812394}
  MINUS {?item wdt:P31 wd:Q105815710}
  MINUS {?item wdt:P31 wd:Q3982337}
  MINUS {?item wdt:P31 wd:Q11812394}
  MINUS {?item wdt:P31 wd:Q30941437}
  MINUS {?item wdt:P31 wd:Q11074464}
  MINUS {?item wdt:P31 wd:Q20819922}
  MINUS {?item wdt:P31 wd:Q742421}
  MINUS {?item wdt:P31 wd:Q101040848}
  MINUS {?item wdt:P31 wd:Q106040099}
  MINUS {?item wdt:P452 wd:Q4373046}
  MINUS {?item wdt:P452 wd:Q185529}
}
