SELECT
  ?item ?imdb ?wikiprojLabel
#  ?retrievedLabel ?object_named_asLabel
#  ?dep_rankLabel ?alt_nameLabel
#  ?refCountryLabel ?archiveurlLabel ?subjectnameLabel
WHERE
{
  {
    SELECT ?item ?imdb
    WHERE {
      ?item wdt:P345 ?imdb.
      ?item p:P345 ?check.
      ?check prov:wasDerivedFrom ?refc.
    }
    LIMIT 50000 OFFSET %s
  }

  OPTIONAL {?item p:P345 [ prov:wasDerivedFrom [ pr:P143 ?wikiproj ] ] }
#  OPTIONAL {?item p:P345 [ prov:wasDerivedFrom [ pr:P813 ?retrieved ] ] }
#  OPTIONAL {?item p:P345 [ prov:wasDerivedFrom [ pr:P1932 ?object_named_as ] ] }
#  OPTIONAL {?item p:P345 [ prov:wasDerivedFrom [ pr:P2241 ?dep_rank ] ] }
#  OPTIONAL {?item p:P345 [ prov:wasDerivedFrom [ pr:P4970 ?alt_name ] ] }
#  OPTIONAL {?item p:P345 [ prov:wasDerivedFrom [ pr:P17 ?refCountry ] ] }
#  OPTIONAL {?item p:P345 [ prov:wasDerivedFrom [ pr:P1065 ?archiveurl ] ] }
#  OPTIONAL {?item p:P345 [ prov:wasDerivedFrom [ pr:P1810 ?subjectname ] ] }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
